spring:
  cloud:
    config:
      server:
        git:
          uri: git@gitlab.testops.vip:TestOps/betacoffee/configures.git

  profiles:
    active: dev,local,test

  security:
    user:
      name: liudao
      password: 123456
 
server:
  port: 10001
